server:
  port: 9000
spring:
  application:
    name: coupon-gategay

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /coupon
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /coupon-template/**
      serviceId: eureka-client-coupon-template
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

# 负载均衡
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000

