spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: server1
  client:
    #是否默认从Eureka Server获取注册信息，默认是true，如果是一个单节点Eureka Server，
    #不需要同步其他节点,设置为false
    fetch-registry: false
    #是否将自己注册到Eureka Server，默认是true，
    register-with-eureka: false
    #设置Eureka Server所在的地址，查询服务和注册扶额u都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
